conf/modules.config
modules/local/openms/decoydatabase/functions.nf
modules/local/openms/decoydatabase/main.nf
modules/local/openms/indexpeptides/functions.nf
modules/local/openms/indexpeptides/main.nf
modules/local/openms/indexpeptides/meta.yml
modules/local/openms/mzmlindexing/main.nf
modules/local/openms/mzmlindexing/meta.yml
modules/local/openms/openmspeakpicker/functions.nf
modules/local/openms/openmspeakpicker/main.nf
modules/local/openms/openmspeakpicker/meta.yml
modules/local/openms/thirdparty/searchenginecomet/functions.nf
modules/local/openms/thirdparty/searchenginecomet/main.nf
modules/local/openms/thirdparty/searchenginecomet/meta.yml
modules/local/openms/thirdparty/searchenginemsgf/functions.nf
modules/local/openms/thirdparty/searchenginemsgf/main.nf
modules/local/openms/thirdparty/searchenginemsgf/meta.yml
modules/local/thermorawfileparser/main.nf
modules/local/thermorawfileparser/meta.yml
nextflow.config
nextflow_schema.json
subworkflows/local/create_input_channel.nf
subworkflows/local/databasesearchengines.nf
subworkflows/local/file_preparation.nf
workflows/tmt.nf

Add DatabaseSearchEngines Subworkflow

---

.gitignore
modules/local/openms/consensusid/main.nf
modules/local/openms/decoydatabase/main.nf
modules/local/openms/epifany/main.nf
modules/local/openms/extractpsmfeature/main.nf
modules/local/openms/falsediscoveryrate/main.nf
modules/local/openms/filemerge/main.nf
modules/local/openms/idconflictresolver/main.nf
modules/local/openms/idfilter/main.nf
modules/local/openms/idmapper/main.nf
modules/local/openms/idpep/main.nf
modules/local/openms/idscoreswitcher/main.nf
modules/local/openms/indexpeptides/main.nf
modules/local/openms/isobaricanalyzer/main.nf
modules/local/openms/msstatsconverter/main.nf
modules/local/openms/mzmlindexing/main.nf
modules/local/openms/openmspeakpicker/main.nf
modules/local/openms/proteininference/main.nf
modules/local/openms/proteinquantifier/main.nf
nextflow.config

docker openms 6.0 -> 2.7pre

---

.nf-core.yml
bin/check_samplesheet.py
bin/scrape_software_versions.py
conf/modules.config
conf/test_lfq.config
modules/local/openms/indexpeptides/main.nf
modules/local/openms/thirdparty/searchenginecomet/main.nf
modules/local/openms/thirdparty/searchenginemsgf/main.nf
modules/local/pmultiqc/functions.nf
modules/local/pmultiqc/main.nf
modules/local/pmultiqc/meta.yml
subworkflows/local/proteinquant.nf
workflows/lfq.nf
workflows/tmt.nf

add pmulitqc

---

conf/modules.config
modules/local/openms/thirdparty/searchenginemsgf/main.nf
subworkflows/local/file_preparation.nf
subworkflows/local/proteininference.nf
workflows/lfq.nf
workflows/tmt.nf

fixed bug and publish files

---

docs/formats.rst
docs/index.rst
docs/introduction.rst

Readthedocs

---

modules/local/openms/consensusid/main.nf
modules/local/openms/decoydatabase/main.nf
modules/local/openms/epifany/main.nf
modules/local/openms/extractpsmfeature/main.nf
modules/local/openms/falsediscoveryrate/main.nf
modules/local/openms/filemerge/main.nf
modules/local/openms/idconflictresolver/main.nf
modules/local/openms/idfilter/main.nf
modules/local/openms/idmapper/main.nf
modules/local/openms/idpep/main.nf
modules/local/openms/idscoreswitcher/main.nf
modules/local/openms/indexpeptides/main.nf
modules/local/openms/isobaricanalyzer/main.nf
modules/local/openms/msstatsconverter/main.nf
modules/local/openms/mzmlindexing/main.nf
modules/local/openms/openmspeakpicker/main.nf
modules/local/openms/proteininference/main.nf
modules/local/openms/proteinquantifier/main.nf
modules/local/openms/proteomicslfq/main.nf
modules/local/openms/thirdparty/luciphoradapter/main.nf
modules/local/openms/thirdparty/percolator/main.nf
modules/local/openms/thirdparty/searchenginecomet/main.nf
modules/local/openms/thirdparty/searchenginemsgf/main.nf
modules/local/samplesheet_check.nf

improvements

---

modules/local/openms/consensusid/main.nf
modules/local/openms/decoydatabase/main.nf
modules/local/openms/epifany/main.nf
modules/local/openms/extractpsmfeature/main.nf
modules/local/openms/falsediscoveryrate/main.nf
modules/local/openms/filemerge/main.nf
modules/local/openms/idconflictresolver/main.nf
modules/local/openms/idfilter/main.nf
modules/local/openms/idmapper/main.nf
modules/local/openms/idpep/main.nf
modules/local/openms/idscoreswitcher/main.nf
modules/local/openms/indexpeptides/main.nf
modules/local/openms/isobaricanalyzer/main.nf
modules/local/openms/msstatsconverter/main.nf
modules/local/openms/mzmlindexing/main.nf
modules/local/openms/openmspeakpicker/main.nf
modules/local/openms/proteininference/main.nf
modules/local/openms/proteinquantifier/main.nf
modules/local/openms/proteomicslfq/main.nf
modules/local/openms/thirdparty/luciphoradapter/main.nf
modules/local/openms/thirdparty/percolator/main.nf
modules/local/openms/thirdparty/searchenginecomet/main.nf
modules/local/openms/thirdparty/searchenginemsgf/main.nf

improvements conda

---

modules/local/openms/consensusid/main.nf
modules/local/openms/epifany/main.nf
modules/local/openms/extractpsmfeature/main.nf
modules/local/openms/falsediscoveryrate/main.nf
modules/local/openms/filemerge/main.nf
modules/local/openms/idconflictresolver/main.nf
modules/local/openms/idfilter/main.nf
modules/local/openms/idmapper/main.nf
modules/local/openms/idpep/main.nf
modules/local/openms/idscoreswitcher/main.nf
modules/local/openms/indexpeptides/main.nf
modules/local/openms/isobaricanalyzer/main.nf
modules/local/openms/msstatsconverter/main.nf
modules/local/openms/mzmlindexing/main.nf
modules/local/openms/openmspeakpicker/main.nf
modules/local/openms/proteininference/main.nf
modules/local/openms/proteinquantifier/main.nf
modules/local/openms/proteomicslfq/main.nf
modules/local/openms/thirdparty/luciphoradapter/main.nf
modules/local/openms/thirdparty/percolator/main.nf
modules/local/openms/thirdparty/searchenginecomet/main.nf
modules/local/openms/thirdparty/searchenginemsgf/main.nf

improvements 

---

modules/local/thermorawfileparser/main.nf

conda improvements

---

modules/local/pmultiqc/main.nf

improve conda

---

.gitignore
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf

conda increase to 0.0.19

---

modules/local/openms/consensusid/main.nf
modules/local/openms/decoydatabase/main.nf
modules/local/openms/epifany/main.nf
modules/local/openms/extractpsmfeature/main.nf
modules/local/openms/falsediscoveryrate/main.nf
modules/local/openms/filemerge/main.nf
modules/local/openms/idconflictresolver/main.nf
modules/local/openms/idfilter/main.nf
modules/local/openms/idmapper/main.nf
modules/local/openms/idpep/main.nf
modules/local/openms/idscoreswitcher/main.nf
modules/local/openms/indexpeptides/main.nf
modules/local/openms/isobaricanalyzer/main.nf
modules/local/openms/msstatsconverter/main.nf
modules/local/openms/mzmlindexing/main.nf
modules/local/openms/openmspeakpicker/main.nf
modules/local/openms/proteininference/main.nf
modules/local/openms/proteinquantifier/main.nf
modules/local/openms/proteomicslfq/main.nf
modules/local/openms/thirdparty/luciphoradapter/main.nf
modules/local/openms/thirdparty/percolator/main.nf
modules/local/openms/thirdparty/searchenginecomet/main.nf
modules/local/openms/thirdparty/searchenginemsgf/main.nf

openms in bioconda

---

modules/nf-core/modules/multiqc/main.nf

openms-2.7 in bioconda

---

modules/local/openms/proteininference/main.nf
modules/local/openms/proteomicslfq/main.nf

rollback inference 

---

nextflow.config

ebicluster

---

modules/local/openms/idmapper/main.nf
nextflow.config

minor change

---

conf/modules.config
modules/local/openms/consensusid/main.nf
modules/local/openms/decoydatabase/main.nf
modules/local/openms/falsediscoveryrate/main.nf
modules/local/openms/filemerge/main.nf
modules/local/openms/idconflictresolver/main.nf
modules/local/openms/idfilter/main.nf
modules/local/openms/idmapper/main.nf
modules/local/openms/idpep/main.nf
modules/local/openms/idscoreswitcher/main.nf
modules/local/openms/indexpeptides/main.nf
modules/local/openms/isobaricanalyzer/main.nf
modules/local/openms/msstatsconverter/main.nf
modules/local/openms/mzmlindexing/main.nf
modules/local/openms/openmspeakpicker/main.nf
modules/local/openms/proteininference/main.nf
modules/local/openms/proteinquantifier/main.nf
modules/local/openms/proteomicslfq/main.nf

TMT improvements using openms=2.8.0dev

---

docs/dia.rst
docs/formats.rst

[DOC] fix and extend formats

---

docs/comet.rst
docs/consensusid.rst
docs/fdr.rst
docs/formats.rst
docs/identification.rst
docs/introduction.rst
docs/msgf.rst
docs/percolator.rst
docs/preprocessing.rst

[DOC] Restructuring of ID subworkflow documentation

---

docs/dda.rst
docs/identification.rst

[DOC] try sidebar with toc

---

Makefile
docs/conf.py
make.bat

forgot files

---

.nf-core.yml

Utils updated

---

conf/test_dia.config
modules/local/diannsearch/main.nf
nextflow.config
nextflow_schema.json

minor changes to improve CI speed 

---

.github/workflows/awsfulltest.yml
.github/workflows/awstest.yml
.gitpod.yml

Template update 2.3.2

---

modules/local/diannsearch/main.nf
modules/local/librarygeneration/main.nf

diann 1.8.1

---

CHANGELOG.md
conf/modules.config
conf/test_localize.config
docs/output.md
docs/usage.md
nextflow.config
subworkflows/local/create_input_channel.nf

skip msstats tests in PTM tests

---

workflows/dia.nf
workflows/lfq.nf
workflows/quantms.nf
workflows/tmt.nf

add msstats_in

---

modules/local/diannconvert/main.nf

fix version

---

.gitignore
bin/check_samplesheet.py
bin/diann_convert.py

Code maintenance

---

modules/local/pmultiqc/main.nf

Update pmultiqc module to 0.0.14

---

modules/local/diannconvert/main.nf
modules/local/mzmlstatistics/main.nf
modules/local/pmultiqc/main.nf

pmultiqc move from 0.0.17 -> 0.0.18

---

CHANGELOG.md
modules/local/diannconvert/main.nf
modules/local/generate_diann_cfg/main.nf
modules/local/pmultiqc/main.nf
modules/local/preprocess_expdesign.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf

pmultiqc:0.0.18 -> 0.0.19
sdrf-pipelines:0.0.21 -> 0.0.22

pmultiqc:0.0.18 -> 0.0.19

---

modules/local/openms/thirdparty/searchenginemsgf/main.nf

Add max_missed_cleavages option to msgf

---

bin/mzml_statistics.py
modules/local/individual_final_analysis/meta.yml
modules/local/mzmlstatistics/main.nf
modules/local/mzmlstatistics/meta.yml
subworkflows/local/file_preparation.nf

Parallel mzml_statistics

---

bin/diann_convert.py

small change.

---

modules/local/openms/thirdparty/searchenginesage/main.nf
subworkflows/local/create_input_channel.nf

Fixing bug https://github.com/bigbio/quantms/issues/278

Fixing multiple bugs of sage quantms

---

bin/msstats_tmt.R
modules/local/preprocess_expdesign.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf

sdrf-pipelines version 0.0.24 and parameters for msstats tmt

---

modules/local/openms/proteomicslfq/main.nf

id transfer threshold update

---

modules/local/openms/extractpsmfeatures/main.nf
modules/local/openms/thirdparty/percolator/main.nf

updating percolator for testing 

---

modules/local/decompress_dotd/main.nf
modules/local/dotd_to_mqc/main.nf

First iteration of bug fixing in Bruker support

---

modules/local/diannconvert/main.nf
modules/local/pmultiqc/main.nf
modules/local/tdf2mzml/main.nf

pmultiqc 0.21 -> 0.22

---

modules/local/silicolibrarygeneration/main.nf

error fixed docker hub diann

---

modules/local/diann_preliminary_analysis/main.nf
workflows/dia.nf

fixed errors

---

modules/local/pmultiqc/main.nf
modules/local/preprocess_expdesign.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf

sdrf-pipelines 0.0.24 -> 0.0.25

---

modules/local/openms/thirdparty/searchenginemsgf/main.nf

Chymotrypsin -> Chymotrypsin/P in MSGF+

---

modules/local/pmultiqc/main.nf

pmultiqc 0.0.25

---

modules/local/pmultiqc/main.nf

pmultiqc 0.0.24

---

modules/local/preprocess_expdesign.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf

sdrf-pipelines 0.0.25 -> 0.0.26

---

.github/workflows/ci.yml
modules/local/preprocess_expdesign.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf

The following PR updates to 0.0.27. This new version allows the sdrf sample metadata validation to use not only ols for validation but also use local files to search terms from ontologies and validate the sdrf.

Update sdrf-pipelines 0.0.26 -> 0.0.27

---

.github/workflows/ci.yml
bin/check_samplesheet.py
modules/local/extract_sample/main.nf
modules/local/generate_diann_cfg/main.nf
modules/local/preprocess_expdesign.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf
nextflow.config
nextflow_schema.json

sdrf-pipelines to 0.0.29

---

CITATIONS.md
nextflow.config
nextflow_schema.json

Minor changes including docs and nextflow configs

---

modules/local/tdf2mzml/main.nf

tdf2mzml in bigbio

---

CHANGELOG.md
modules/local/add_sage_feat/main.nf
modules/local/diannconvert/main.nf
modules/local/extract_psm/main.nf
modules/local/extract_psm/meta.yml
modules/local/generate_diann_cfg/main.nf
modules/local/ms2rescore/main.nf
modules/local/mzmlstatistics/main.nf
modules/local/preprocess_expdesign.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf
modules/local/spectrum2features/main.nf

quantms-utils 0.0.8 -> 0.0.9

---

.github/CONTRIBUTING.md
.nf-core.yml
CHANGELOG.md
docs/README.md
docs/output.md
modules/local/generate_diann_cfg/main.nf

minor updating doc

---

conf/pride_codon_slurm.config
modules/local/openms/thirdparty/msgfdb_indexing/main.nf

update container for msgf_plus indexing.

---

conf/pride_codon_slurm.config

changes in pride slurm config

---

modules/local/openms/thirdparty/msgfdb_indexing/main.nf

update msgf_plus process to remove the process tag

---

conf/pride_codon_slurm.config

minor changes in pride resource limits

---

.github/workflows/ci.yml
modules/local/add_sage_feat/main.nf
modules/local/diannconvert/main.nf
modules/local/extract_psm/main.nf
modules/local/extract_sample/main.nf
modules/local/generate_diann_cfg/main.nf
modules/local/ms2rescore/main.nf
modules/local/mzmlstatistics/main.nf
modules/local/preprocess_expdesign.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf
modules/local/spectrum2features/main.nf

This PR solves the issue #447.

quanmts-utils 0.0.15 -> 0.0.17: ms2rescore bug solved

---

conf/base.config
modules/local/generate_diann_cfg/main.nf
modules/local/preprocess_expdesign.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf

We are exploring multiple runs and the details of each process. In this PR, we are trying to optimize some of the obvious processes. The full issue and discussion can be found here #455

Optimization of process resources

---

.github/workflows/linting_comment.yml
.nf-core.yml
.pre-commit-config.yaml
modules.json
modules/nf-core/multiqc/environment.yml
modules/nf-core/multiqc/main.nf
modules/nf-core/multiqc/tests/main.nf.test.snap
nextflow.config
nextflow_schema.json
ro-crate-metadata.json

more help added to MSGF protocol, update template 3.2.0

---

modules/local/ms2rescore/main.nf

change the error ms2rescore to the corresponding search engine

---

.github/workflows/ci.yml
.github/workflows/extended_ci.yml
.nf-core.yml
conf/test_dda_id.config
conf/test_dia.config
conf/test_full_dia.config
conf/test_full_tmt.config
conf/test_latest_dia.config
conf/test_lfq.config
conf/test_lfq_sage.config
conf/test_localize.config
conf/test_tmt.config
conf/test_tmt_corr.config
modules/local/ms2rescore/main.nf
modules/local/mzmlstatistics/main.nf

Changes the CI/CD for testing Dev OpenMS in Dev PRs

---

modules/local/ms2rescore/main.nf
modules/local/openms/consensusid/main.nf
modules/local/openms/decoydatabase/main.nf
modules/local/openms/epifany/main.nf
modules/local/openms/extractpsmfeatures/main.nf
modules/local/openms/falsediscoveryrate/main.nf
modules/local/openms/filemerge/main.nf
modules/local/openms/idconflictresolver/main.nf
modules/local/openms/idfilter/main.nf
modules/local/openms/idmapper/main.nf
modules/local/openms/idmerger/main.nf
modules/local/openms/idripper/main.nf
modules/local/openms/idscoreswitcher/main.nf
modules/local/openms/indexpeptides/main.nf
modules/local/openms/isobaricanalyzer/main.nf
modules/local/openms/msstatsconverter/main.nf
modules/local/openms/mzmlindexing/main.nf
modules/local/openms/openmspeakpicker/main.nf
modules/local/openms/proteininference/main.nf
modules/local/openms/proteinquantifier/main.nf
modules/local/openms/proteomicslfq/main.nf
modules/local/openms/thirdparty/luciphoradapter/main.nf
modules/local/openms/thirdparty/percolator/main.nf
modules/local/openms/thirdparty/searchenginecomet/main.nf
modules/local/openms/thirdparty/searchenginemsgf/main.nf
modules/local/openms/thirdparty/searchenginesage/main.nf

Fixed small bug with singularity in OpenMS

---

CHANGELOG.md
conf/test_dda_id.config
modules/local/diannconvert/main.nf
modules/local/extract_psm/main.nf
modules/local/extract_sample/main.nf
modules/local/generate_diann_cfg/main.nf
modules/local/ms2rescore/main.nf
modules/local/mzmlstatistics/main.nf
modules/local/pmultiqc/main.nf
modules/local/preprocess_expdesign.nf
modules/local/psm_clean/main.nf
modules/local/psm_clean/meta.yml
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf
modules/local/spectrum2features/main.nf
nextflow.config
nextflow_schema.json
subworkflows/local/dda_id.nf
subworkflows/local/psmrescoring.nf
workflows/dia.nf

quantms-rescoring 0.0.9 and cleaning spectra step

---

.github/workflows/ci.yml
.github/workflows/extended_ci.yml
modules/local/ms2rescore/main.nf
nextflow.config

update name of variable in process

---

.nf-core.yml
CHANGELOG.md
modules/local/pmultiqc/main.nf
ro-crate-metadata.json

pmultiqc updated 0.0.27 version

---

CHANGELOG.md
modules/local/diannconvert/main.nf
modules/local/extract_psm/main.nf
modules/local/extract_sample/main.nf
modules/local/generate_diann_cfg/main.nf
modules/local/mzmlstatistics/main.nf
modules/local/preprocess_expdesign.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf
modules/local/spectrum2features/main.nf

quantms-utils 0.0.23 & sdrf-pipelines 0.0.32

---

workflows/dia.nf
workflows/quantms.nf

add mztab to results for pmultiqc

---

modules/local/pmultiqc/main.nf

pmultiqc version increased to 0.0.28. Error fixed with diann_report.tsv

---

nextflow.config

add Fabian Egli as contributor

---

modules/local/spectrum2features/main.nf

small bug in SNR step

---

CHANGELOG.md
modules/local/msstats/main.nf
nextflow.config

Minor refinements with quantms code style, update msstats LFQ -> 4.14.0

---

.nf-core.yml
CHANGELOG.md
nextflow.config
ro-crate-metadata.json

prepare for release 1.4.1
