bigbio/quantms

modules/local/openms/consensusid/main.nf
modules/local/openms/decoydatabase/main.nf
modules/local/openms/epifany/main.nf
modules/local/openms/extractpsmfeature/main.nf
modules/local/openms/falsediscoveryrate/main.nf
modules/local/openms/filemerge/main.nf
modules/local/openms/idconflictresolver/main.nf
modules/local/openms/idfilter/main.nf
modules/local/openms/idmapper/main.nf
modules/local/openms/idpep/main.nf
modules/local/openms/idscoreswitcher/main.nf
modules/local/openms/indexpeptides/main.nf
modules/local/openms/isobaricanalyzer/main.nf
modules/local/openms/msstatsconverter/main.nf
modules/local/openms/mzmlindexing/main.nf
modules/local/openms/openmspeakpicker/main.nf
modules/local/openms/proteininference/main.nf
modules/local/openms/proteinquantifier/main.nf
modules/local/openms/proteomicslfq/main.nf
modules/local/openms/thirdparty/luciphoradapter/main.nf
modules/local/openms/thirdparty/percolator/main.nf
modules/local/openms/thirdparty/searchenginecomet/main.nf
modules/local/openms/thirdparty/searchenginemsgf/main.nf

openms-2.7 in bioconda

---

conf/modules.config
modules/local/openms/idmapper/main.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf

idmapper changes

---

.nf-core.yml
assets/multiqc_config.yaml
conf/modules.config
modules/local/openms/consensusid/main.nf
modules/local/openms/decoydatabase/main.nf
modules/local/openms/epifany/main.nf
modules/local/openms/extractpsmfeature/main.nf
modules/local/openms/falsediscoveryrate/main.nf
modules/local/openms/filemerge/main.nf
modules/local/openms/idconflictresolver/main.nf
modules/local/openms/idfilter/main.nf
modules/local/openms/idmapper/main.nf
modules/local/openms/idpep/main.nf
modules/local/openms/idscoreswitcher/main.nf
modules/local/openms/indexpeptides/main.nf
modules/local/openms/isobaricanalyzer/main.nf
modules/local/openms/msstatsconverter/main.nf
modules/local/openms/mzmlindexing/main.nf
modules/local/openms/openmspeakpicker/main.nf
modules/local/openms/proteininference/main.nf
modules/local/openms/proteinquantifier/main.nf
modules/local/openms/proteomicslfq/main.nf
modules/local/openms/thirdparty/luciphoradapter/main.nf
modules/local/openms/thirdparty/percolator/main.nf
modules/local/openms/thirdparty/searchenginecomet/main.nf
modules/local/openms/thirdparty/searchenginemsgf/main.nf
modules/local/pmultiqc/main.nf
nextflow.config
workflows/quantms.nf

remove multiqc

---

conf/test_dia.config

increase min_peptide in test

---

modules/local/diann_preliminary_analysis/main.nf
modules/local/diann_preliminary_analysis/meta.yml
nextflow.config
nextflow_schema.json

restruct DIA-NN step2

---

conf/modules.config
conf/test_lfq.config
conf/test_localize.config
conf/test_tmt.config
modules/local/openms/falsediscoveryrate/main.nf
modules/local/openms/proteomicslfq/main.nf
nextflow.config
nextflow_schema.json

[FIX/FEATURE] Add exp. wide PSM-FDR. Rename FDR params. Slightly change usage.

---

bin/diann_convert.py
conf/test_full_dia.config
conf/test_full_lfq.config
modules/local/diannsummary/main.nf
nextflow.config
nextflow_schema.json
subworkflows/local/create_input_channel.nf

minor fixed

---

bin/diann_convert.py
modules/local/diannconvert/main.nf
workflows/dia.nf

small fixs

---

bin/mzml_statistics.py
modules/local/diannconvert/main.nf
modules/local/mzmlstatistics/main.nf
modules/local/mzmlstatistics/meta.yml
modules/local/openms/consensusid/main.nf
modules/local/openms/decoydatabase/main.nf
modules/local/openms/epifany/main.nf
modules/local/openms/extractpsmfeatures/main.nf
modules/local/openms/falsediscoveryrate/main.nf
modules/local/openms/filemerge/main.nf
modules/local/openms/idconflictresolver/main.nf
modules/local/openms/idfilter/main.nf
modules/local/openms/idmapper/main.nf
modules/local/openms/idpep/main.nf
modules/local/openms/idscoreswitcher/main.nf
modules/local/openms/indexpeptides/main.nf
modules/local/openms/isobaricanalyzer/main.nf
modules/local/openms/msstatsconverter/main.nf
modules/local/openms/mzmlindexing/main.nf
modules/local/openms/openmspeakpicker/main.nf
modules/local/openms/proteininference/main.nf
modules/local/pmultiqc/main.nf
subworkflows/local/file_preparation.nf
workflows/quantms.nf

testing with dev version of OpenMS 2.8.0

---

modules/local/diannconvert/main.nf
modules/local/msstats/main.nf
modules/local/msstatstmt/main.nf
modules/local/openms/msstatsconverter/main.nf
modules/local/openms/proteininference/main.nf
modules/local/openms/proteinquantifier/main.nf
modules/local/openms/proteomicslfq/main.nf
modules/local/pmultiqc/main.nf
nextflow.config
nextflow_schema.json

update some process to openms dev

---

modules/local/openms/proteomicslfq/main.nf
nextflow.config
nextflow_schema.json
workflows/dia.nf

major refactoring of PLFQ to a probabilistic approach

---

CHANGELOG.md
README.md

Improving doc

---

nextflow.config
nextflow_schema.json
workflows/dia.nf

library creation

---

modules/local/openms/thirdparty/searchenginecomet/main.nf
modules/local/openms/thirdparty/searchenginesage/main.nf
nextflow.config
nextflow_schema.json

This PR add the parameter of charge to SAGE processor and other properties

---

bin/extract_sample.py
bin/ms2rescore_cli.py
bin/psm_conversion.py
conf/modules.config
conf/test_full_lfq.config
conf/test_full_tmt.config
conf/test_localize.config
modules.json
modules/local/extract_sample/main.nf
modules/local/extract_sample/meta.yml
modules/local/ms2rescore/main.nf
modules/local/ms2rescore/meta.yml
modules/local/openms/consensusid/main.nf
modules/local/openms/extractpsmfeatures/main.nf
modules/local/openms/idmerger/main.nf
modules/local/openms/idmerger/meta.yml
modules/local/openms/idripper/main.nf
modules/local/openms/idripper/meta.yml
modules/local/openms/thirdparty/percolator/main.nf
nextflow.config
nextflow_schema.json
subworkflows/local/dda_id.nf
subworkflows/local/psmrescoring.nf
subworkflows/nf-core/utils_nfcore_pipeline/main.nf
workflows/quantms.nf

add optional ms2rescore step

---

bin/ms2rescore_cli.py
conf/modules.config
modules/local/extract_psm/main.nf
modules/local/ms2rescore/main.nf
modules/local/mzmlstatistics/main.nf
nextflow.config
nextflow_schema.json
subworkflows/local/dda_id.nf
subworkflows/local/id.nf
subworkflows/local/psmrescoring.nf
workflows/lfq.nf
workflows/tmt.nf

ms2rescore for quant workflow and fixed some bugs

---

modules/local/mzmlstatistics/main.nf

I'm wondering how the tests in the id_only PR could pass but I am pretty sure that is a bug.
I cannot get a DIANN workflow to work without this.

[HOTFIX] pipeline failing without id_only because of missing outputs

---

CHANGELOG.md
bin/check_samplesheet.py
modules/local/samplesheet_check.nf
nextflow.config
nextflow_schema.json
subworkflows/local/input_check.nf

This PR is our hotfix to address #385 by adding the `validate_ontologies` parameter. When `false` the `SAMPLESHEET_CHECK` process will only parse the SDRF file, but will not perform validation. 
I'm sure there is a more elegant solution, but I thought this might be helpful as a starting point. Please feel free to ignore if it doesn't go in the right direction.
I'm also happy to add a test if someone could point me in the right direction 😉.

Make validation of ontology terms optional

---

CHANGELOG.md
modules/local/decompress_dotd/main.nf

This PR adds a verification step to unpacking tar archives in the DECOMPRESS process, addressing #395. Specifically it:
1. Checks that all files in the archive are present when unpacked
2. Checks that all of the files are the same size.
The main reason for the PR being slightly more complicated than originally planned is that `tar d` will fail with exit code 0 if *anything* about a file has changed - including permissions and such. Given differences between the computing platform where the file may have been generated and where the workflow is executed, I think this is too strict.
I haven't included tests in the PR, put it seems to have worked well on a workflow I'm currently executing on ~7,000 input Bruker .d files.

Add verification for tar unpacking

---

CHANGELOG.md
nextflow.config
nextflow_schema.json
workflows/dia.nf

This PR adds a sorting step to the input channel prior to the random selection of files. It also adds a new parameter to control the random seed.
Fixes #399.

Make files selected with `random_preanalysis` reproducible.

---

.github/workflows/ci.yml
.nf-core.yml
modules/local/add_sage_feat/main.nf
modules/local/diannconvert/main.nf
modules/local/extract_psm/main.nf
modules/local/extract_sample/main.nf
modules/local/generate_diann_cfg/main.nf
modules/local/ms2rescore/main.nf
modules/local/mzmlstatistics/main.nf
modules/local/preprocess_expdesign.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf
modules/local/spectrum2features/main.nf
nextflow.config

quantms 0.0.10 -> 0.0.11

---

modules/local/thermorawfileparser/main.nf

___
enhancement
___
- Reverted the `thermorawfileparser` version from 1.4.5 to 1.3.4 in the Nextflow process configuration.
- Updated the container image references to align with the reverted version, ensuring compatibility and stability.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>main.nf</strong><dd><code>Revert thermorawfileparser to version 1.3.4</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
modules/local/thermorawfileparser/main.nf
<li>Reverted <code>thermorawfileparser</code> version from 1.4.5 to 1.3.4.<br> <li> Updated container image references to match the reverted …

Revert thermorawfileparser

---

.github/workflows/ci.yml
.github/workflows/diann_private.yml
conf/dev.config
conf/pride_codon_slurm.config
conf/test_latest_dia.config
modules/local/add_sage_feat/main.nf
modules/local/assemble_empirical_library/main.nf
modules/local/diann_preliminary_analysis/main.nf
modules/local/diannconvert/main.nf
modules/local/diannsummary/main.nf
modules/local/extract_psm/main.nf
modules/local/extract_sample/main.nf
modules/local/generate_diann_cfg/main.nf
modules/local/individual_final_analysis/main.nf
modules/local/ms2rescore/main.nf
modules/local/mzmlstatistics/main.nf
modules/local/preprocess_expdesign.nf
modules/local/samplesheet_check.nf
modules/local/sdrfparsing/main.nf
modules/local/silicolibrarygeneration/main.nf
modules/local/spectrum2features/main.nf
nextflow.config
nextflow_schema.json
subworkflows/local/create_input_channel.nf
workflows/dia.nf

Improving configs for OpenMS dev and DIANN versions over 1.8.1

---

conf/dev.config
conf/pride_codon_slurm.config

update confs - dev and pride ebi

---

conf/test_dda_id.config
modules/local/spectrum2features/main.nf

Fixing bug issues with SNR; quantms-utils -> quantms-rescoring
